# Generated by Django 5.1.4 on 2024-12-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='users_using_tag',
        ),
    ]
